package softwaremodelingproject;

import java.awt.CardLayout;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import softwaremodelingproject.Product;
import javax.swing.*;
import javax.swing.text.PlainDocument;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Alexis
 */
public class SoftwareModelingFrame extends javax.swing.JFrame {

    double checkoutTotal = 0;
    ArrayList<Product> checkoutList = new ArrayList<>();
    ArrayList<Product> productList = new ArrayList<>();
    NumberFormat formatter = new DecimalFormat("#0.00");
    /**
     * Creates new form SoftwareModelingFram
     */
    public SoftwareModelingFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startPanel = new javax.swing.JPanel();
        manageButton = new javax.swing.JButton();
        checkoutButton = new javax.swing.JButton();
        checkoutPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        OrderArea = new javax.swing.JTextArea();
        checkoutCancelButton = new javax.swing.JButton();
        checkoutLookupButton = new javax.swing.JButton();
        finishAndPayButton = new javax.swing.JButton();
        totalLabel = new javax.swing.JLabel();
        managePanel = new javax.swing.JPanel();
        addNewButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        manageCancelButton = new javax.swing.JButton();
        addProductPanel = new javax.swing.JPanel();
        addProductLabel = new javax.swing.JLabel();
        nameAddLabel = new javax.swing.JLabel();
        idAddLabel = new javax.swing.JLabel();
        priceAddLabel = new javax.swing.JLabel();
        quantityAddLabel = new javax.swing.JLabel();
        vendorAddLabel = new javax.swing.JLabel();
        expirationAddLabel = new javax.swing.JLabel();
        nameAddField = new javax.swing.JTextField();
        idAddField = new javax.swing.JTextField();
        priceAddField = new javax.swing.JTextField();
        quantityAddField = new javax.swing.JTextField();
        vendorAddField = new javax.swing.JTextField();
        expirationAddField = new javax.swing.JTextField();
        addSubmitButton = new javax.swing.JButton();
        addDateFormatLabel = new javax.swing.JLabel();
        addProductCancel = new javax.swing.JButton();
        editProductPanel = new javax.swing.JPanel();
        editProductLabel = new javax.swing.JLabel();
        nameEditLabel = new javax.swing.JLabel();
        idEditLabel = new javax.swing.JLabel();
        priceEditLabel = new javax.swing.JLabel();
        quantityEditLabel = new javax.swing.JLabel();
        vendorEditLabel = new javax.swing.JLabel();
        expirationEditLabel = new javax.swing.JLabel();
        nameEditField = new javax.swing.JTextField();
        idEditField = new javax.swing.JTextField();
        priceEditField = new javax.swing.JTextField();
        quantityEditField = new javax.swing.JTextField();
        vendorEditField = new javax.swing.JTextField();
        expirationEditField = new javax.swing.JTextField();
        editSubmitButton = new javax.swing.JButton();
        editDateFormatLabel = new javax.swing.JLabel();
        editProductCancel = new javax.swing.JButton();
        checkoutLookupPanel = new javax.swing.JPanel();
        checkoutSearchLabel = new javax.swing.JLabel();
        checkoutSearchField = new javax.swing.JTextField();
        checkoutIdLabel = new javax.swing.JLabel();
        checkoutIdField = new javax.swing.JTextField();
        checkoutLookupSubmit = new javax.swing.JButton();
        checkoutSearchButton = new javax.swing.JButton();
        checkoutLookupCancel = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        checkoutLookupArea = new javax.swing.JTextArea();
        checkoutQuantityLabel = new javax.swing.JLabel();
        checkoutQuantityField = new javax.swing.JTextField();
        editLookupPanel = new javax.swing.JPanel();
        editSearchLabel = new javax.swing.JLabel();
        editSearchField = new javax.swing.JTextField();
        editLookupIdLabel = new javax.swing.JLabel();
        editLookupIdField = new javax.swing.JTextField();
        editLookupSubmit = new javax.swing.JButton();
        editSearchButton = new javax.swing.JButton();
        editLookupCancel = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        editLookupArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Frame");
        getContentPane().setLayout(new java.awt.CardLayout());

        manageButton.setText("Manage");
        manageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageButtonActionPerformed(evt);
            }
        });

        checkoutButton.setText("Checkout");
        checkoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout startPanelLayout = new javax.swing.GroupLayout(startPanel);
        startPanel.setLayout(startPanelLayout);
        startPanelLayout.setHorizontalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startPanelLayout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addComponent(checkoutButton)
                .addGap(110, 110, 110)
                .addComponent(manageButton)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        startPanelLayout.setVerticalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPanelLayout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manageButton)
                    .addComponent(checkoutButton))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        getContentPane().add(startPanel, "panelOne");

        OrderArea.setEditable(false);
        OrderArea.setColumns(20);
        OrderArea.setRows(5);
        OrderArea.setText("Order:\n");
        jScrollPane1.setViewportView(OrderArea);

        checkoutCancelButton.setText("Cancel");
        checkoutCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutCancelButtonActionPerformed(evt);
            }
        });

        checkoutLookupButton.setText("Look Up");
        checkoutLookupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutLookupButtonActionPerformed(evt);
            }
        });

        finishAndPayButton.setText("Finish + Pay");
        finishAndPayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishAndPayButtonActionPerformed(evt);
            }
        });

        totalLabel.setText("Total: $0.00");

        javax.swing.GroupLayout checkoutPanelLayout = new javax.swing.GroupLayout(checkoutPanel);
        checkoutPanel.setLayout(checkoutPanelLayout);
        checkoutPanelLayout.setHorizontalGroup(
            checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkoutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totalLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95)
                .addGroup(checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkoutLookupButton)
                    .addComponent(finishAndPayButton)
                    .addComponent(checkoutCancelButton))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        checkoutPanelLayout.setVerticalGroup(
            checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkoutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(checkoutPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalLabel))
                    .addGroup(checkoutPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(checkoutLookupButton)
                        .addGap(18, 18, 18)
                        .addComponent(finishAndPayButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkoutCancelButton)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(checkoutPanel, "panelTwo");

        addNewButton.setText("Add New");
        addNewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        manageCancelButton.setText("Cancel");
        manageCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout managePanelLayout = new javax.swing.GroupLayout(managePanel);
        managePanel.setLayout(managePanelLayout);
        managePanelLayout.setHorizontalGroup(
            managePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(manageCancelButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(managePanelLayout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addComponent(addNewButton)
                .addGap(114, 114, 114)
                .addComponent(updateButton)
                .addContainerGap(90, Short.MAX_VALUE))
        );
        managePanelLayout.setVerticalGroup(
            managePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managePanelLayout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addGroup(managePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addNewButton)
                    .addComponent(updateButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(manageCancelButton)
                .addContainerGap())
        );

        getContentPane().add(managePanel, "card4");

        addProductLabel.setText("Add New Product");

        nameAddLabel.setText("Name:");

        idAddLabel.setText("Product ID:");

        priceAddLabel.setText("Price:");

        quantityAddLabel.setText("Quantity:");

        vendorAddLabel.setText("Vendor:");

        expirationAddLabel.setText("Expiration Date:");
        expirationAddLabel.setToolTipText("");

        nameAddField.setText("Name");
        nameAddField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameAddFieldActionPerformed(evt);
            }
        });

        idAddField.setText("Product ID");

        priceAddField.setText("Price");

        quantityAddField.setText("Quantity");

        vendorAddField.setText("Vendor");

        expirationAddField.setText("Expiration Date");

        addSubmitButton.setLabel("Submit");
        addSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSubmitButtonActionPerformed(evt);
            }
        });

        addDateFormatLabel.setText("yyyy-mm-dd");

        addProductCancel.setText("Cancel");
        addProductCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addProductPanelLayout = new javax.swing.GroupLayout(addProductPanel);
        addProductPanel.setLayout(addProductPanelLayout);
        addProductPanelLayout.setHorizontalGroup(
            addProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addProductPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addProductPanelLayout.createSequentialGroup()
                        .addComponent(nameAddLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameAddField, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE))
                    .addGroup(addProductPanelLayout.createSequentialGroup()
                        .addComponent(addProductLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(addProductPanelLayout.createSequentialGroup()
                        .addComponent(idAddLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idAddField))
                    .addGroup(addProductPanelLayout.createSequentialGroup()
                        .addComponent(priceAddLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(priceAddField))
                    .addGroup(addProductPanelLayout.createSequentialGroup()
                        .addComponent(quantityAddLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quantityAddField))
                    .addGroup(addProductPanelLayout.createSequentialGroup()
                        .addComponent(vendorAddLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vendorAddField))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addProductPanelLayout.createSequentialGroup()
                        .addComponent(addProductCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addSubmitButton))
                    .addGroup(addProductPanelLayout.createSequentialGroup()
                        .addComponent(expirationAddLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addProductPanelLayout.createSequentialGroup()
                                .addComponent(addDateFormatLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(expirationAddField))))
                .addContainerGap())
        );
        addProductPanelLayout.setVerticalGroup(
            addProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addProductPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addProductLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameAddLabel)
                    .addComponent(nameAddField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idAddLabel)
                    .addComponent(idAddField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceAddLabel)
                    .addComponent(priceAddField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantityAddLabel)
                    .addComponent(quantityAddField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vendorAddLabel)
                    .addComponent(vendorAddField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expirationAddLabel)
                    .addComponent(expirationAddField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addDateFormatLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(addProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addSubmitButton)
                    .addComponent(addProductCancel))
                .addContainerGap())
        );

        getContentPane().add(addProductPanel, "card5");

        editProductLabel.setText("Edit Product");

        nameEditLabel.setText("Name:");

        idEditLabel.setText("Product ID:");
        idEditLabel.setEnabled(false);

        priceEditLabel.setText("Price");

        quantityEditLabel.setText("Quantity:");

        vendorEditLabel.setText("Vendor:");

        expirationEditLabel.setText("Expiration Date:");
        expirationEditLabel.setToolTipText("");

        nameEditField.setText("Name");
        nameEditField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameEditFieldActionPerformed(evt);
            }
        });

        idEditField.setText("Product ID");
        idEditField.setEnabled(false);

        priceEditField.setText("Price");

        quantityEditField.setText("Quantity");

        vendorEditField.setText("Vendor");
        vendorEditField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendorEditFieldActionPerformed(evt);
            }
        });

        expirationEditField.setText("Expiration Date");

        editSubmitButton.setLabel("Submit");
        editSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSubmitButtonActionPerformed(evt);
            }
        });

        editDateFormatLabel.setText("yyyy-mm-dd");

        editProductCancel.setText("Cancel");
        editProductCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProductCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editProductPanelLayout = new javax.swing.GroupLayout(editProductPanel);
        editProductPanel.setLayout(editProductPanelLayout);
        editProductPanelLayout.setHorizontalGroup(
            editProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editProductPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editProductPanelLayout.createSequentialGroup()
                        .addComponent(nameEditLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameEditField, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE))
                    .addGroup(editProductPanelLayout.createSequentialGroup()
                        .addComponent(idEditLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idEditField))
                    .addGroup(editProductPanelLayout.createSequentialGroup()
                        .addComponent(priceEditLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(priceEditField))
                    .addGroup(editProductPanelLayout.createSequentialGroup()
                        .addComponent(quantityEditLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quantityEditField))
                    .addGroup(editProductPanelLayout.createSequentialGroup()
                        .addComponent(vendorEditLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vendorEditField))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editProductPanelLayout.createSequentialGroup()
                        .addComponent(editProductCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editSubmitButton))
                    .addGroup(editProductPanelLayout.createSequentialGroup()
                        .addComponent(editProductLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(editProductPanelLayout.createSequentialGroup()
                        .addComponent(expirationEditLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(editProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editProductPanelLayout.createSequentialGroup()
                                .addComponent(editDateFormatLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(expirationEditField))))
                .addContainerGap())
        );
        editProductPanelLayout.setVerticalGroup(
            editProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editProductPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editProductLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameEditLabel)
                    .addComponent(nameEditField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idEditLabel)
                    .addComponent(idEditField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceEditLabel)
                    .addComponent(priceEditField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantityEditLabel)
                    .addComponent(quantityEditField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vendorEditLabel)
                    .addComponent(vendorEditField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expirationEditLabel)
                    .addComponent(expirationEditField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editDateFormatLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(editProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editSubmitButton)
                    .addComponent(editProductCancel))
                .addContainerGap())
        );

        getContentPane().add(editProductPanel, "card5");

        checkoutSearchLabel.setText("Search");
        checkoutSearchLabel.setEnabled(false);

        checkoutSearchField.setText("Search");
        checkoutSearchField.setEnabled(false);
        checkoutSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutSearchFieldActionPerformed(evt);
            }
        });

        checkoutIdLabel.setText("Enter ID");

        checkoutIdField.setText("ID");

        checkoutLookupSubmit.setText("Submit");
        checkoutLookupSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutLookupSubmitActionPerformed(evt);
            }
        });

        checkoutSearchButton.setText("Search");
        checkoutSearchButton.setEnabled(false);

        checkoutLookupCancel.setText("Cancel");
        checkoutLookupCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutLookupCancelActionPerformed(evt);
            }
        });

        checkoutLookupArea.setEditable(false);
        checkoutLookupArea.setColumns(20);
        checkoutLookupArea.setRows(5);
        jScrollPane3.setViewportView(checkoutLookupArea);

        checkoutQuantityLabel.setText("Quantity");

        checkoutQuantityField.setText("Quantity");

        javax.swing.GroupLayout checkoutLookupPanelLayout = new javax.swing.GroupLayout(checkoutLookupPanel);
        checkoutLookupPanel.setLayout(checkoutLookupPanelLayout);
        checkoutLookupPanelLayout.setHorizontalGroup(
            checkoutLookupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkoutLookupPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(checkoutLookupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkoutSearchField)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkoutLookupPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(checkoutSearchButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkoutLookupPanelLayout.createSequentialGroup()
                        .addGroup(checkoutLookupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(checkoutLookupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(checkoutIdField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(checkoutLookupCancel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(checkoutSearchLabel)
                            .addComponent(checkoutIdLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(checkoutLookupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkoutQuantityLabel)
                            .addComponent(checkoutLookupSubmit)
                            .addComponent(checkoutQuantityField, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        checkoutLookupPanelLayout.setVerticalGroup(
            checkoutLookupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkoutLookupPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(checkoutLookupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(checkoutLookupPanelLayout.createSequentialGroup()
                        .addComponent(checkoutSearchLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkoutSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(checkoutSearchButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(checkoutLookupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkoutIdLabel)
                            .addComponent(checkoutQuantityLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(checkoutLookupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkoutIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkoutQuantityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                        .addGroup(checkoutLookupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkoutLookupSubmit)
                            .addComponent(checkoutLookupCancel))))
                .addContainerGap())
        );

        getContentPane().add(checkoutLookupPanel, "card7");

        editSearchLabel.setText("Search");
        editSearchLabel.setEnabled(false);

        editSearchField.setText("Search");
        editSearchField.setEnabled(false);
        editSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSearchFieldActionPerformed(evt);
            }
        });

        editLookupIdLabel.setText("Enter ID");

        editLookupIdField.setText("ID");

        editLookupSubmit.setText("Submit");
        editLookupSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editLookupSubmitActionPerformed(evt);
            }
        });

        editSearchButton.setText("Search");
        editSearchButton.setEnabled(false);

        editLookupCancel.setText("Cancel");
        editLookupCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editLookupCancelActionPerformed(evt);
            }
        });

        editLookupArea.setEditable(false);
        editLookupArea.setColumns(20);
        editLookupArea.setRows(5);
        jScrollPane4.setViewportView(editLookupArea);

        javax.swing.GroupLayout editLookupPanelLayout = new javax.swing.GroupLayout(editLookupPanel);
        editLookupPanel.setLayout(editLookupPanelLayout);
        editLookupPanelLayout.setHorizontalGroup(
            editLookupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editLookupPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(editLookupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editSearchField)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editLookupPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(editSearchButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editLookupPanelLayout.createSequentialGroup()
                        .addGroup(editLookupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editLookupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(editLookupIdField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(editLookupCancel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(editSearchLabel)
                            .addComponent(editLookupIdLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(editLookupSubmit)))
                .addContainerGap())
        );
        editLookupPanelLayout.setVerticalGroup(
            editLookupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editLookupPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editLookupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(editLookupPanelLayout.createSequentialGroup()
                        .addComponent(editSearchLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(editSearchButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editLookupIdLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editLookupIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                        .addGroup(editLookupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editLookupSubmit)
                            .addComponent(editLookupCancel))))
                .addContainerGap())
        );

        getContentPane().add(editLookupPanel, "card7");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutButtonActionPerformed
        checkoutPanel.setVisible(true);
        startPanel.setVisible(false);
        productList = ProductDAO.findAll();
        Collections.sort(productList);
    }//GEN-LAST:event_checkoutButtonActionPerformed

    private void nameAddFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameAddFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameAddFieldActionPerformed

    private void checkoutCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutCancelButtonActionPerformed
        startPanel.setVisible(true);
        checkoutPanel.setVisible(false);
        OrderArea.setText("Order:\n");
        totalLabel.setText("Total: $0.00");
        checkoutList = new ArrayList<>();
        productList = new ArrayList<>();
        checkoutTotal = 0;
    }//GEN-LAST:event_checkoutCancelButtonActionPerformed

    private void manageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageButtonActionPerformed
        managePanel.setVisible(true);
        startPanel.setVisible(false);
    }//GEN-LAST:event_manageButtonActionPerformed

    private void addNewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewButtonActionPerformed
        addProductPanel.setVisible(true);
        managePanel.setVisible(false);
    }//GEN-LAST:event_addNewButtonActionPerformed

    private void nameEditFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameEditFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameEditFieldActionPerformed

    private void manageCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCancelButtonActionPerformed
        managePanel.setVisible(false);
        startPanel.setVisible(true);
    }//GEN-LAST:event_manageCancelButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        managePanel.setVisible(false);
        editLookupPanel.setVisible(true);
        editLookupArea.setText(null);
        for (Product p : ProductDAO.findAll()) {
            editLookupArea.append(p.getName() + "\tID: " + p.getId() + "\n"
                + "   In Stock: " + p.getQuantity() + "\t   $" + formatter.format(p.getPrice()) + "\n");
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void checkoutSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutSearchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkoutSearchFieldActionPerformed

    private void addSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSubmitButtonActionPerformed
        String name = nameAddField.getText();
        int ID = 0;
        double price = 0;
        int quantity = 0;
        try {
            ID = Integer.parseInt(idEditField.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "ID must be an integer.");
        }
        try {
            price = Double.parseDouble(priceEditField.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Price must be a number.");
        }
        try {
            quantity = Integer.parseInt(idEditField.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Quantity must be an integer.");
        }
        String vendor = vendorAddField.getText();
        String expiration = expirationAddField.getText();
        Calendar exp;
        SimpleDateFormat format1 = new SimpleDateFormat("yyyy-MM-dd");
            try {
                if (expiration.equals("null")) {
                    exp = null;
                } else {
                    exp = Calendar.getInstance();
                    exp.setTime(format1.parse(expiration));
                }
            ProductDAO.insertProduct(name, ID, price, quantity, vendor, exp);
            addProductPanel.setVisible(false);
            managePanel.setVisible(true);
        } catch (ParseException ex) {
            Logger.getLogger(SoftwareModelingFrame.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Please enter properly formatted date.");
        }
    }//GEN-LAST:event_addSubmitButtonActionPerformed

    private void vendorEditFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendorEditFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vendorEditFieldActionPerformed

    private void checkoutLookupCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutLookupCancelActionPerformed
        checkoutLookupPanel.setVisible(false);
        checkoutPanel.setVisible(true);
    }//GEN-LAST:event_checkoutLookupCancelActionPerformed

    private void checkoutLookupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutLookupButtonActionPerformed
        checkoutPanel.setVisible(false);
        checkoutLookupPanel.setVisible(true);
        checkoutLookupArea.setText(null);
        for (Product p : productList) {
            if (p.getQuantity() > 0) {
                checkoutLookupArea.append(p.getName() + "\tID: " + p.getId() + "\n"
                    + "   In Stock: " + p.getQuantity() + "\t   $" + formatter.format(p.getPrice()) + "\n");
            }
        }
    }//GEN-LAST:event_checkoutLookupButtonActionPerformed

    private void checkoutLookupSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutLookupSubmitActionPerformed
        try {
            int id = Integer.parseInt(checkoutIdField.getText());
            int quantity = Integer.parseInt(checkoutQuantityField.getText());
            Product p = new Product();
            int low = 0;
            int high = productList.size();
            int i = 0;
            while (low <= high) {
                i = low + ((high - low) / 2);
                if (productList.get(i).getId() == id) {
                    p = productList.get(i);
                    break;
                } else if (productList.get(i).getId() < id) {
                    low = i + 1;
                } else {
                    high = i - 1;
                }
            }
            if (p.getName().equals("null")) {
                JOptionPane.showMessageDialog(this, "Please enter a valid Product ID.");
            } else if (quantity < 0) {
                JOptionPane.showMessageDialog(this, "Please enter a valid quantity.");
            } else if (quantity > p.getQuantity()) {
                JOptionPane.showMessageDialog(this, "Quantity cannot exceed the amount of product in stock.");
            } else if (quantity <= p.getQuantity()) {
                double totalPrice = quantity * p.getPrice();
                checkoutTotal += totalPrice;
                OrderArea.append(p.getName() + "\tID: " + p.getId() + "\n"
                    + "   Quantity: " + quantity + "\t   Total: $" + formatter.format(totalPrice) + "\n");
                checkoutList.add(p);
                totalLabel.setText("Total: $" + formatter.format(checkoutTotal));
                productList.get(i).setQuantity(p.getQuantity() - quantity);
                checkoutLookupPanel.setVisible(false);
                checkoutPanel.setVisible(true);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Please enter properly formatted numbers.");
        }
    }//GEN-LAST:event_checkoutLookupSubmitActionPerformed

    private void editSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSearchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editSearchFieldActionPerformed

    private void editLookupSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editLookupSubmitActionPerformed
        try {
            int id = Integer.parseInt(editLookupIdField.getText());
            Product p = ProductDAO.findById(id);
            if (p.getName().equals("null")) {
                JOptionPane.showMessageDialog(this, "Please enter a valid Product ID.");
            } else if (!p.getName().equals("null")) {
                nameEditField.setText(p.getName());
                idEditField.setText("" + p.getId());
                priceEditField.setText("" + formatter.format(p.getPrice()));
                quantityEditField.setText("" + p.getQuantity());
                vendorEditField.setText(p.getVendor());
                Calendar expiration = p.getExpiration();
                String formatted = "";
                if (expiration == null) {
                    formatted = "null";
                } else {
                    SimpleDateFormat format1 = new SimpleDateFormat("yyyy-MM-dd");
                    formatted = format1.format(expiration.getTime());
                }
                expirationEditField.setText(formatted);
                editLookupPanel.setVisible(false);
                editProductPanel.setVisible(true);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Please enter properly formatted numbers.");
        }
        
    }//GEN-LAST:event_editLookupSubmitActionPerformed

    private void editLookupCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editLookupCancelActionPerformed
        editLookupPanel.setVisible(false);
        managePanel.setVisible(true);
    }//GEN-LAST:event_editLookupCancelActionPerformed

    private void editProductCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProductCancelActionPerformed
        editProductPanel.setVisible(false);
        editLookupPanel.setVisible(true);
    }//GEN-LAST:event_editProductCancelActionPerformed

    private void addProductCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductCancelActionPerformed
        addProductPanel.setVisible(false);
        managePanel.setVisible(true);
    }//GEN-LAST:event_addProductCancelActionPerformed

    private void editSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSubmitButtonActionPerformed
        String name = nameEditField.getText();
        int ID = 0;
        double price = 0;
        int quantity = 0;
        try {
            ID = Integer.parseInt(idEditField.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "ID must be an integer.");
        }
        try {
            price = Double.parseDouble(priceEditField.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Price must be a number.");
        }
        try {
            quantity = Integer.parseInt(idEditField.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Quantity must be an integer.");
        }
        String vendor = vendorEditField.getText();
        String expiration = expirationEditField.getText();
        Calendar exp;
        SimpleDateFormat format1 = new SimpleDateFormat("yyyy-MM-dd");
        try {
            if (expiration.equals("null")) {
                exp = null;
            } else {
                exp = Calendar.getInstance();
                exp.setTime(format1.parse(expiration));
            }
            ProductDAO.updateProduct(name, ID, price, quantity, vendor, exp);
            editProductPanel.setVisible(false);
            managePanel.setVisible(true);
        } catch (ParseException ex) {
            Logger.getLogger(SoftwareModelingFrame.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Please enter properly formatted date.");
        }
    }//GEN-LAST:event_editSubmitButtonActionPerformed

    private void finishAndPayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishAndPayButtonActionPerformed
        for (Product p : productList) {
            //is CheckoutList obsolete?
            ProductDAO.updateProduct(p.getName(), p.getId(), p.getPrice(), p.getQuantity(), 
                    p.getVendor(), p.getExpiration());
        }
        startPanel.setVisible(true);
        checkoutPanel.setVisible(false);
        OrderArea.setText("Order: ");
        totalLabel.setText("Total: $0.00");
        checkoutList = new ArrayList<>();
        productList = new ArrayList<>();
        checkoutTotal = 0;
    }//GEN-LAST:event_finishAndPayButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SoftwareModelingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SoftwareModelingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SoftwareModelingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SoftwareModelingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SoftwareModelingFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea OrderArea;
    private javax.swing.JLabel addDateFormatLabel;
    private javax.swing.JButton addNewButton;
    private javax.swing.JButton addProductCancel;
    private javax.swing.JLabel addProductLabel;
    private javax.swing.JPanel addProductPanel;
    private javax.swing.JButton addSubmitButton;
    private javax.swing.JButton checkoutButton;
    private javax.swing.JButton checkoutCancelButton;
    private javax.swing.JTextField checkoutIdField;
    private javax.swing.JLabel checkoutIdLabel;
    private javax.swing.JTextArea checkoutLookupArea;
    private javax.swing.JButton checkoutLookupButton;
    private javax.swing.JButton checkoutLookupCancel;
    private javax.swing.JPanel checkoutLookupPanel;
    private javax.swing.JButton checkoutLookupSubmit;
    private javax.swing.JPanel checkoutPanel;
    private javax.swing.JTextField checkoutQuantityField;
    private javax.swing.JLabel checkoutQuantityLabel;
    private javax.swing.JButton checkoutSearchButton;
    private javax.swing.JTextField checkoutSearchField;
    private javax.swing.JLabel checkoutSearchLabel;
    private javax.swing.JLabel editDateFormatLabel;
    private javax.swing.JTextArea editLookupArea;
    private javax.swing.JButton editLookupCancel;
    private javax.swing.JTextField editLookupIdField;
    private javax.swing.JLabel editLookupIdLabel;
    private javax.swing.JPanel editLookupPanel;
    private javax.swing.JButton editLookupSubmit;
    private javax.swing.JButton editProductCancel;
    private javax.swing.JLabel editProductLabel;
    private javax.swing.JPanel editProductPanel;
    private javax.swing.JButton editSearchButton;
    private javax.swing.JTextField editSearchField;
    private javax.swing.JLabel editSearchLabel;
    private javax.swing.JButton editSubmitButton;
    private javax.swing.JTextField expirationAddField;
    private javax.swing.JLabel expirationAddLabel;
    private javax.swing.JTextField expirationEditField;
    private javax.swing.JLabel expirationEditLabel;
    private javax.swing.JButton finishAndPayButton;
    private javax.swing.JTextField idAddField;
    private javax.swing.JLabel idAddLabel;
    private javax.swing.JTextField idEditField;
    private javax.swing.JLabel idEditLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton manageButton;
    private javax.swing.JButton manageCancelButton;
    private javax.swing.JPanel managePanel;
    private javax.swing.JTextField nameAddField;
    private javax.swing.JLabel nameAddLabel;
    private javax.swing.JTextField nameEditField;
    private javax.swing.JLabel nameEditLabel;
    private javax.swing.JTextField priceAddField;
    private javax.swing.JLabel priceAddLabel;
    private javax.swing.JTextField priceEditField;
    private javax.swing.JLabel priceEditLabel;
    private javax.swing.JTextField quantityAddField;
    private javax.swing.JLabel quantityAddLabel;
    private javax.swing.JTextField quantityEditField;
    private javax.swing.JLabel quantityEditLabel;
    private javax.swing.JPanel startPanel;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JButton updateButton;
    private javax.swing.JTextField vendorAddField;
    private javax.swing.JLabel vendorAddLabel;
    private javax.swing.JTextField vendorEditField;
    private javax.swing.JLabel vendorEditLabel;
    // End of variables declaration//GEN-END:variables
}
